version: '3'
services:
  sonarqube:
    build: .
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
    ports:
      - "9000:9000"
      - "9092:9092"
    depends_on:
      - db
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
      - PGDATA=/var/lib/postgresql/data/pgdata
